name: dependency_validator
version: 1.4.1
description: Checks for missing, under-promoted, over-promoted, and unused dependencies.
homepage: https://github.com/Workiva/dependency_validator
authors:
  - Jace Hensley <jace.hensley@workiva.com>
  - Evan Weible <evan.weible@workiva.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: '>=0.13.7 <2.0.0'
  logging: ^0.11.3+1
  path: ^1.4.2
  pub_semver: ^1.4.1
  yaml: ^2.1.13

dev_dependencies:
  test: ^1.9.4
  test_descriptor: ^1.2.0

executables:
  dependency_validator:
