name: dependency_validator
version: 1.2.0
description: Checks for missing, under-promoted, over-promoted, and unused dependencies.
homepage: https://github.com/Workiva/dependency_validator
authors:
  - Jace Hensley <jace.hensley@workiva.com>
  - Evan Weible <evan.weible@workiva.com>

environment:
  sdk: '>=1.24.2 <3.0.0'

dependencies:
  args: '>=0.13.7 <2.0.0'
  logging: ^0.11.3+1
  path: ^1.4.2
  pub_semver: ^1.4.1
  yaml: ^2.1.13

dev_dependencies:
  build_runner: '>=0.6.0 <1.0.0'
  build_test: '>=0.9.0 <1.0.0'
  coverage: '>=0.9.3 <0.13.0'
  dart_style: ^1.0.8
  test: '>=0.12.30 <2.0.0'

executables:
  dependency_validator:
