name: dependency_validator
version: 2.0.0-beta
description: Checks for missing, under-promoted, over-promoted, and unused dependencies.
homepage: https://github.com/Workiva/dependency_validator
authors:
  - Jace Hensley <jace.hensley@workiva.com>
  - Evan Weible <evan.weible@workiva.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.0
  build_config: ^0.4.2
  checked_yaml: ^1.0.0
  glob: ^1.2.0
  json_annotation: ^3.0.0
  logging: ^0.11.3+1
  package_config: ^1.9.3
  path: ^1.4.2
  pub_semver: ^1.4.1
  pubspec_parse: ^0.1.5
  yaml: ^2.1.13

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  test: ^1.9.4
  test_descriptor: ^1.2.0
  workiva_analysis_options: ^1.0.0

executables:
  dependency_validator:

dependency_validator:
  exclude:
    - 'test_fixtures/**'
  ignore:
    - json_serializable
    - _foo
    - foo
    - _bar
    - bar
    - foo1
    - foo_foo