name: valid
version: 0.0.0
private: true
environment:
  sdk: '>=1.24.2 <3.0.0'
dependencies:
  logging: any
  yaml: any
  fake_project:
    path: ../fake_project
dev_dependencies:
  dependency_validator:
    path: ../..
  test: any

transformers:
  - dart_to_js_script_rewriter
  - test/pub_serve:
      $include: test/**_test{.*,}.dart